### PR TITLE
Update the schemas

### PR DESCRIPTION
**Pull request by LeeAlephium**
Requires alephium/explorer-backend and alephium/alephium versions to be stable

### CODE REVIEW

**Comment by nop33** [comment]
In our README we say that we'll introduce breaking changes in minor releases. This introduces breaking changes (it'd be nice to keep a list of them as we go, so that I don't have to check all the diff from the previous release to find out what breaks). Should we bump the minor version? Or should we stay at `0.0.x`? Is it expected to have breaking changes in `0.0.x`?

**Comment by LeeAlephium** [comment]
If the readme says there's breaking changes in minor versions and this is a breaking change then yep, let's bump the minor version and I guess add a changelog

**Comment by nop33** [comment]
> Or should we stay at 0.0.x? Is it expected to have breaking changes in 0.0.x?

I think Cheng mentioned once that it's ok to introduce breaking changes in `0.0.x`. But if we all agree that we should bump the minor (which I agree), then let's do it.

/cc @mvaivre

**Review by tdroxler — APPROVED** [review]

**Comment by LeeAlephium** [comment]
Need to downgrade from 1.5 to 1.4 for api-alephium

**Comment by tdroxler** [comment]
I tested the explorer FE with this change, everything looks good

**Comment by LeeAlephium** [comment]
Not approved here but @mvaivre gave me the :+1: on Slack to merge and do a release

**Pull request merged**
