### PR TITLE
Update terser

### PR DESCRIPTION
**Pull request by LeeAlephium**
I also ran `npm version patch` so that's why the package version is updated here - I'll wait to push the tag until the tests pass

### CODE REVIEW

**Comment by mvaivre** [comment]
Quick question: why requesting a review then merge it 4 minutes after?
Why not wait for the review, to make sure Ilias saw it and is aware of what's going on? :P

**Comment by LeeAlephium** [comment]
Since the code had already been reviewed and this was a `npm audit fix` and I thought it'd be merged immediately after the test was successful, I went ahead, because I feel an urgency to get the mobile-wallet perf PR working

**Comment by mvaivre** [comment]
> I went ahead, because I feel an urgency to get the mobile-wallet perf PR working

... wait. I've just read [this comment](https://github.com/alephium/mobile-wallet/pull/20#discussion_r937714802) in the mobile-wallet perf PR, where you explain that you took shortcuts on the mobile because you're focusing on the desktop-wallet, so I'm a bit flabbergasted : it seems rather contradictory.

And also, I'm not sure I understand how merging this without approval would help with the "mobile-wallet urgency"? Anyway, not a big deal, but it's so important to just do those little things properly, it helps a lot with communication and collaboration. 
BTW, if you need clarification about priorities and "urgencies" (hint: there are no urgency right now, we try to avoid these), please don't hesitate to ask! :)

As always: we don't want to take shortcuts, we don't want to introduce dirty code, we don't want to compromise on testing, we don't want to rush into things when it's not needed. Focus on quality and good communication are keys! So let's make sure we work together on those 🙌

**Comment by nop33** [comment]
> Since the code had already been reviewed

I would have caught the version bump commit however, so no, the code was not reviewed :P

**Comment by LeeAlephium** [comment]
I don't consider a data change to be a code change, but regardless I **must not** be so hasty when merging and releasing a version like this. I understand it's excusable now but it definitely won't be as we grow!

**Pull request merged**
