### PR TITLE
Upgrade explorer schema to 1.8.0-rc1

### PR DESCRIPTION
**Pull request by nop33**
This PR brings the address discovery endpoint and a few other beautiful changes to the `next-stack` branch.

Related to:
- https://github.com/alephium/explorer/issues/111
- https://github.com/alephium/desktop-wallet/issues/276

### CODE REVIEW

**Review by LeeAlephium — APPROVED** [review]
Just a note for myself: tokens and logging related upgrade

**Comment by LeeAlephium** [comment]
I think `amount` became `outputRef.spent`

**Comment by LeeAlephium** [comment]
I corrected the tests for next-stack earlier: how come it's back?

**Comment by nop33** [comment]
> I corrected the tests for next-stack earlier: how come it's back?

Probably because you upgraded to explorer 1.7 and I upgraded it even further to 1.8?

**Review by LeeAlephium — APPROVED** [review]
:+1:

**Pull request merged**
