### PR TITLE
Make sure correct files are included in package

### PR DESCRIPTION
**Pull request by nop33**
Based on the [docs](https://docs.npmjs.com/cli/v7/commands/npm-publish) of `npm publish`, I run `npx npm-packlist` to verify the list of files added in the NPM package. To my surprise, I saw files like the following being included:
```
dev/network-4/db/LOCK
dev/network-4/db/LOG
dev/network-4/db/MANIFEST-000004
dev/network-4/db/OPTIONS-000021
dev/network-4/db/OPTIONS-000023
dev/network-4/network.conf
dev/network-4/system.conf
dev/alephium-1.3.0-rc8.jar
```

These files are generated when the script `npm run devnet:start` runs. Even though this script does not run in the GitHub action that publishes the NPM package, I still think it's necessary to explicitly ignore these files and only include the `dev/user.conf` file.

### CODE REVIEW

**Comment by mvaivre** [comment]
Good catch. One little fear: how will we remember to edit the included files if one day we need more than the user.conf? I'm afraid we could miss this and publish the package without noticing that some files are missing..

**Comment by nop33** [comment]
That's a good point. Reading the [docs](https://docs.npmjs.com/cli/v7/commands/npm-publish#files-included-in-package) I understand that if we don't specify the `"files"` attribute in package.json, then we can control which files are added using `.gitignore` and `.npmignore`. Need to investigate.

**Comment by nop33** [comment]
I've deleted the `"files"` package.json attribute adn created a `.npmignore` file which overrides the `.gitignore` file. The new list that `npx npm-packlist` returns is the following:

```
README.md
LICENSE
package.json
dev/user.conf

dist/
scripts/
templates/
contracts/
```

**Review by mvaivre — APPROVED** [review]
That's great, much more explicit 👌

**Pull request merged**
